version: '3.9'

services:
  db:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=dashboard
    ports:
      - '5430:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
    restart: always
    ports:
      - '5005:5005'
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/dashboard?sslmode=disable

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: always
    ports:
      - '8085:80'
    depends_on:
      - backend

volumes:
  postgres_data:
